version: "3.8"
name: link-generator-backend
services:
  link-generator:
    container_name: link-generator-backend
    build: "."
    restart: always
    ports:
      - "4000:4000"
    environment:
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE_NAME=${SQL_DATABASE_NAME}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - REDIS_ADDR=redis-server:6379
    depends_on:
      - redis
      # - db
    networks:
      - web

  redis:
    container_name: redis-server
    image: "redis:latest"
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - web

  # db:
  #   container_name: postgres-db
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${SQL_USER}
  #     POSTGRES_PASSWORD: ${SQL_PASSWORD}
  #     POSTGRES_DB: ${SQL_DATABASE_NAME}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - web

networks:
  web:
    external: true

volumes:
  redis-data:
    name: redis-data
  # pgdata:
  #   name: pgdata